### ISSUE TITLE
Common: fix PathNotFoundException in PII enrichment

### ISSUE THREAD

**Issue by chuwy** [snowplow/enrich#339]
This line: https://github.com/snowplow/enrich/blob/85ce299623f68244cf1dd7251287982be8b8eb17/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/pii/PiiPseudonymizerEnrichment.scala#L273-L276 can throw following exception:

```
com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['a','b','c','d','e'] in path $['properties']['foo'] but found 'null'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JacksonJsonNodeJsonProvider'.
    at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:71)
    at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:81)
    at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:79)
    at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:81)
    at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:79)
    at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
    at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
    at com.jayway.jsonpath.JsonPath.map(JsonPath.java:244)
    at com.jayway.jsonpath.internal.JsonContext.map(JsonContext.java:161)
    at com.jayway.jsonpath.internal.JsonContext.map(JsonContext.java:155)
    at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.pii.PiiJson.jsonPathReplace(PiiPseudonymizerEnrichment.scala:275)
    at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.pii.PiiJson.$anonfun$modifyObjectIfSchemaMatches$6(PiiPseudonymizerEnrichment.scala:255)
    at scala.Option.map(Option.scala:230)
```

**Comment by benjben** [comment]
To add more details, this is happening when we want to hash `foo.a`, but `foo` (whose type is `["object", "null"]`) is `null`
