### ISSUE TITLE
Common: fix NullPointerException in RedirectAdapter

### ISSUE THREAD

**Issue by benjben** [snowplow/enrich#341]
Stacktrace:

```
java.lang.NullPointerException: null
    at io.circe.Printer$PrintingFolder.onString(Printer.scala:278)
    at io.circe.Printer$PrintingFolder.onString(Printer.scala:262)
    at io.circe.Json$JString.foldWith(Json.scala:302)
    at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:326)
    at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
    at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
    at io.circe.Json$JObject.foldWith(Json.scala:364)
    at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:326)
    at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
    at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
    at io.circe.Json$JObject.foldWith(Json.scala:364)
    at io.circe.Printer$PrintingFolder.onArray(Printer.scala:323)
    at io.circe.Printer$PrintingFolder.onArray(Printer.scala:262)
    at io.circe.Json$JArray.foldWith(Json.scala:333)
    at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:326)
    at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
    at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
    at io.circe.Json$JObject.foldWith(Json.scala:364)
    at io.circe.Printer.pretty(Printer.scala:194)
    at io.circe.Json.noSpaces(Json.scala:116)
    at com.snowplowanalytics.snowplow.enrich.common.adapters.registry.snowplow.RedirectAdapter$.newCo$1(RedirectAdapter.scala:104)
    at com.snowplowanalytics.snowplow.enrich.common.adapters.registry.snowplow.RedirectAdapter$.toRawEvents(RedirectAdapter.scala:106)
    at com.snowplowanalytics.snowplow.enrich.common.adapters.AdapterRegistry.toRawEvents(AdapterRegistry.scala:98)
    at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$.processEvents(EtlPipeline.scala:63)
    at com.snowplowanalytics.snowplow.enrich.stream.sources.Source.$anonfun$enrichEvents$1(Source.scala:207)
    at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:329)
    at com.snowplowanalytics.snowplow.enrich.stream.sources.Source.enrichEvents(Source.scala:207)
    at com.snowplowanalytics.snowplow.enrich.stream.sources.Source.$anonfun$enrichAndStoreEvents$1(Source.scala:249)
    at scala.collection.immutable.List.flatMap(List.scala:338)
    at com.snowplowanalytics.snowplow.enrich.stream.sources.Source.enrichAndStoreEvents(Source.scala:249)
    at com.snowplowanalytics.snowplow.enrich.stream.sources.KinesisSource$RawEventProcessor.processRecordsWithRetries(KinesisSource.scala:221)
    at com.snowplowanalytics.snowplow.enrich.stream.sources.KinesisSource$RawEventProcessor.processRecords(KinesisSource.scala:214)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.callProcessRecords(ProcessTask.java:221)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by benjben** [comment]
Happens when `&u` in the query string (no value specified)

**Comment by benjben** [comment]
Handled by #342
