### ISSUE TITLE
Stream: kinesis partition key fall back to random UUID

### ISSUE THREAD

**Issue by seanhall** [snowplow/enrich#377]
**Project**: Stream Enrich

**Version**: 1.3.2

**Expected behavior**: If Kinesis sink is configured to partition on domain_userid and domain_userid is null, app should fall back safely to another key/value. Config file allows naming a field that doesn't exist as key, but app does not consider a valid key with null values. Should include safety for this.

**Actual behavior**: Enrich gets stuck retrying record, creating a loop and backpressure until the record(s) age off.

**Steps to reproduce**:

 1. Configure enrich to partition on domain_userid.
 2. Emit records from an iOS app (the ObjC SDK does not maintain or send domain_userid) to the collector
 3. On receipt by the enricher, the app chokes on the record: `com.amazonaws.services.kinesis.model.AmazonKinesisException: 10 validation errors detected: Value null at 'records.1.member.partitionKey' failed to satisfy constraint: Member must not be null;` Full trace below.

```
com.amazonaws.services.kinesis.model.AmazonKinesisException: 10 validation errors detected: Value null at 'records.1.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.2.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.3.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.4.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.5.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.6.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.7.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.8.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.9.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.10.member.partitionKey' failed to satisfy constraint: Member must not be null (Service: AmazonKinesis; Status Code: 400; Error Code: ValidationException; Request ID: d18f2220-986d-205c-898d-b3e1bebc1a69)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2388)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2364)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executePutRecords(AmazonKinesisClient.java:1859)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:1834)
	at com.snowplowanalytics.snowplow.enrich.stream.sinks.KinesisSink$$anonfun$multiPut$1.apply(KinesisSink.scala:289)
	at com.snowplowanalytics.snowplow.enrich.stream.sinks.KinesisSink$$anonfun$multiPut$1.apply(KinesisSink.scala:275)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[RecordProcessor-0000] ERROR com.snowplowanalytics.snowplow.enrich.stream.sinks.KinesisSink -   + Retrying in 2542 milliseconds...
[RecordProcessor-0000] ERROR com.snowplowanalytics.snowplow.enrich.stream.sinks.KinesisSink - Writing failed.
com.amazonaws.services.kinesis.model.AmazonKinesisException: 10 validation errors detected: Value null at 'records.1.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.2.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.3.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.4.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.5.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.6.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.7.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.8.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.9.member.partitionKey' failed to satisfy constraint: Member must not be null; Value null at 'records.10.member.partitionKey' failed to satisfy constraint: Member must not be null (Service: AmazonKinesis; Status Code: 400; Error Code: ValidationException; Request ID: c08a7692-b5f8-39e0-9888-e75657cc2a9a)
```

**Comment by chuwy** [comment]
Thanks, @seanhall. 1.4.0 is almost ready for release, schedulling for 1.5.0.

**Comment by seanhall** [comment]
I have a potential fix for this I'd like to push:

in KinesisSink.scala private def multiPut:

```
val testPartitionKey = Option(s)
testPartitionKey match {
  case Some(s) => prre.setPartitionKey(s)
  case None => prre.setPartitionKey(UUID.randomUUID().toString)
}
```

**Comment by istreeter** [comment]
Thanks a lot for contributing a fix @seanhall!  After looking through the code, I think the source of the error is [here](https://github.com/snowplow/enrich/blob/81d108152b54961867cd1f6218b22465afb5c083/modules/stream/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/sources/Source.scala#L185-195) rather than in KinesisSink.  The function `getPropertyValue` claims to return a String, but as you correctly point out it could be null if `domain_userid` is not set.  This is the function where the partition key is calculated.

I will fix that function and we can get this into version 2.0.0 which will be released soon.
